- Regenerate with bashly 0.8.0

diff --git a/git-changelog b/git-changelog
--- a/git-changelog
+++ b/git-changelog
@@ -1,10 +1,17 @@
 #!/usr/bin/env bash
-# This script was generated by bashly (https://github.com/DannyBen/bashly)
+# This script was generated by bashly 0.8.0 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
+# :wrapper.bash3_bouncer
+if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
+  printf "bash version 4 or higher is required\n"
+  exit 1
+fi
+
+# :command.master_script
 # :command.root_command
 root_command() {
-  # :src/root_command.sh
+  # src/root_command.sh
   limit="${args[--tail]}"
   color="${args[--color]}"
   reverse="${args[--reverse]}"
@@ -12,20 +19,20 @@ root_command() {
   save="${args[--save]}"
   tail_one="${args[-1]}"
   tail_two="${args[-2]}"
-  
+
   if [[ -n "$save" ]]; then
     out="CHANGELOG.md"
     reverse=1
   fi
-  
+
   if [[ -n "$tail_one" ]]; then
     limit=1
   fi
-  
+
   if [[ -n "$tail_two" ]]; then
     limit=2
   fi
-  
+
   if [[ -n "$out" ]]; then
     get_markdown "$limit" "off" "$reverse" > "$out"
   else
@@ -42,10 +49,12 @@ version_command() {
 git_changelog_usage() {
   if [[ -n $long_usage ]]; then
     printf "git-changelog - Generate a human-readable change log from a git repository\n"
-    echo 
+    echo
+
   else
     printf "git-changelog - Generate a human-readable change log from a git repository\n"
-    echo 
+    echo
+
   fi
 
   printf "Usage:\n"
@@ -68,33 +77,33 @@ git_changelog_usage() {
     echo "  --tail, -t N"
     printf "    Show only the last N tags\n"
     echo
-    
+
     # :flag.usage
     echo "  --reverse, -r"
     printf "    Show tags in reverse order (newest first)\n"
     echo
-    
+
     # :flag.usage
     echo "  --out, -o PATH"
     printf "    Save output to a file\n"
     echo
-    
+
     # :flag.usage
     echo "  --color, -c MODE"
     printf "    Enable or disable color. Supported modes:\n    - yes, on, always\n    - no, off, never\n    - auto\n"
     printf "    Default: auto\n"
     echo
-    
+
     # :flag.usage
     echo "  --save, -s"
     printf "    Shortcut for '--reverse --out CHANGELOG.md'\n"
     echo
-    
+
     # :flag.usage
     echo "  -1"
     printf "    Shortcut for '--tail 1'\n"
     echo
-    
+
     # :flag.usage
     echo "  -2"
     printf "    Shortcut for '--tail 2'\n"
@@ -102,7 +111,7 @@ git_changelog_usage() {
 
     # :command.usage_examples
     printf "Examples:\n"
-    
+
     printf "  git changelog --tail 3\n"
     printf "  git changelog --out CHANGELOG.md\n"
     printf "  git changelog -r -o CHANGELOG.md\n"
@@ -111,6 +120,30 @@ git_changelog_usage() {
   fi
 }
 
+# :command.normalize_input
+normalize_input() {
+  local arg flags
+
+  while [[ $# -gt 0 ]]; do
+    arg="$1"
+    if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
+      input+=("${BASH_REMATCH[1]}")
+      input+=("${BASH_REMATCH[2]}")
+    elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
+      input+=("${BASH_REMATCH[1]}")
+      input+=("${BASH_REMATCH[2]}")
+    elif [[ $arg =~ ^-([a-zA-Z0-9][a-zA-Z0-9]+)$ ]]; then
+      flags="${BASH_REMATCH[1]}"
+      for (( i=0 ; i < ${#flags} ; i++ )); do
+        input+=("-${flags:i:1}")
+      done
+    else
+      input+=("$arg")
+    fi
+
+    shift
+  done
+}
 # :command.inspect_args
 inspect_args() {
   readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
@@ -120,23 +153,33 @@ inspect_args() {
   else
     echo args: none
   fi
+
+  if (( ${#other_args[@]} )); then
+    echo
+    echo other_args:
+    echo "- \${other_args[*]} = ${other_args[*]}"
+    for i in "${!other_args[@]}"; do
+      echo "- \${other_args[$i]} = ${other_args[$i]}"
+    done
+  fi
 }
 
 # :command.user_lib
-# :src/lib/abort.sh
+# src/lib/abort.sh
 abort() {
   red "$1"
   exit 1
 }
 
-# :src/lib/colors.sh
+# src/lib/colors.sh
 # ---
 # Color functions
 # This file is a part of Bashly standard library
 #
 # Usage:
 # Use any of the functions below to color or format a portion of a string.
-# 
+#
+
 #   echo "before $(red this is red) after"
 #   echo "before $(green_bold this is green_bold) after"
 #
@@ -163,17 +206,17 @@ blue_underlined() { printf "\e[4;34m%b\e[0m\n" "$*"; }
 magenta_underlined() { printf "\e[4;35m%b\e[0m\n" "$*"; }
 cyan_underlined() { printf "\e[4;36m%b\e[0m\n" "$*"; }
 
-# :src/lib/debug.sh
+# src/lib/debug.sh
 debug() {
   echo "DEBUG: $*" >&2
 }
 
-# :src/lib/get_latest_tag.sh
+# src/lib/get_latest_tag.sh
 get_latest_tag() {
   git tag --sort=committerdate --format='%(refname:short)' | grep --color=never -P "^(v[[:digit:]]|[[:digit:]])" | tail -n 1
 }
 
-# :src/lib/get_log.sh
+# src/lib/get_log.sh
 get_log() {
   ref="$1"
 
@@ -182,7 +225,7 @@ get_log() {
   set -e
 }
 
-# :src/lib/get_markdown.sh
+# src/lib/get_markdown.sh
 get_markdown() {
   limit=$1
   color=$2
@@ -199,7 +242,8 @@ get_markdown() {
   [[ -n "$limit" ]] && refs=$(echo "$refs" | tail -n "$limit")
 
   for tag_data in $refs; do
-    IFS=: read -ra data <<< "$tag_data" 
+    IFS=: read -ra data <<< "$tag_data"
+
     tag=${data[0]}
     date=${data[1]}
     ref=${data[2]}
@@ -219,7 +263,7 @@ get_markdown() {
   done
 }
 
-# :src/lib/get_refs.sh
+# src/lib/get_refs.sh
 # Returns an array, where each line is "tag:date:ref"
 # It is the same as get tags, only with added ref
 get_refs() {
@@ -241,34 +285,34 @@ get_refs() {
   fi
 }
 
-# :src/lib/get_sha.sh
+# src/lib/get_sha.sh
 get_sha() {
   ref="$1"
   result=$(git log "$ref" --reverse --format='%h:::%s' | grep --color=never -P ":::- " | tail -n 1)
   echo "${result%:*}"
 }
 
-# :src/lib/get_tags.sh
+# src/lib/get_tags.sh
 get_tags() {
   git tag --sort=committerdate --format='%(refname:short):%(committerdate:short)' | grep --color=never -P "^(v[[:digit:]]|[[:digit:]])"
 }
 
-# :src/lib/has_latest.sh
+# src/lib/has_latest.sh
 # Returns success if the repository has meaningful commits after the last tag
 has_latest() {
   latest_tag=$(get_latest_tag)
   latest_tag_sha=$(get_sha "$latest_tag")
-  head_sha=$(get_sha HEAD) 
+  head_sha=$(get_sha HEAD)
 
   [[ "$latest_tag_sha" != "$head_sha" ]]
 }
 
-# :src/lib/is_tty.sh
+# src/lib/is_tty.sh
 is_tty() {
   [[ -t 1 || -p /dev/stdout ]]
 }
 
-# :src/lib/reverse.sh
+# src/lib/reverse.sh
 # Reverse an array
 # Usage: reverse "${your_array[@]}"
 reverse() {
@@ -276,7 +320,7 @@ reverse() {
   printf '%s\n' "${arr[@]}" | tac
 }
 
-# :src/lib/use_color.sh
+# src/lib/use_color.sh
 use_color() {
   option=${1:-auto}
 
@@ -289,7 +333,7 @@ use_color() {
   fi
 }
 
-# :src/lib/verify_git_repo.sh
+# src/lib/verify_git_repo.sh
 verify_git_repo() {
   if ! git status &> /dev/null ; then
     abort "Not a git repository"
@@ -304,33 +348,34 @@ verify_git_repo() {
 
 # :command.parse_requirements
 parse_requirements() {
-  # :command.fixed_flag_filter
-  case "$1" in
+  # :command.fixed_flags_filter
+  case "${1:-}" in
   --version | -v )
     version_command
     exit
     ;;
-  
+
   --help | -h )
     long_usage=yes
     git_changelog_usage
-    exit 1
+    exit
     ;;
-  
+
   esac
   # :command.environment_variables_filter
   # :command.dependencies_filter
   # :command.command_filter
   action="root"
-  # :command.required_args_filter
-  # :command.required_flags_filter
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
     # :flag.case
     --tail | -t )
-      if [[ $2 ]]; then
+      # :flag.conflicts
+      # :flag.case_arg
+      if [[ -n ${2+x} ]]; then
+        # :flag.validations
         args[--tail]="$2"
         shift
         shift
@@ -339,16 +384,21 @@ parse_requirements() {
         exit 1
       fi
       ;;
-  
+
     # :flag.case
     --reverse | -r )
+      # :flag.conflicts
+      # :flag.case_no_arg
       args[--reverse]=1
       shift
       ;;
-  
+
     # :flag.case
     --out | -o )
-      if [[ $2 ]]; then
+      # :flag.conflicts
+      # :flag.case_arg
+      if [[ -n ${2+x} ]]; then
+        # :flag.validations
         args[--out]="$2"
         shift
         shift
@@ -357,10 +407,13 @@ parse_requirements() {
         exit 1
       fi
       ;;
-  
+
     # :flag.case
     --color | -c )
-      if [[ $2 ]]; then
+      # :flag.conflicts
+      # :flag.case_arg
+      if [[ -n ${2+x} ]]; then
+        # :flag.validations
         args[--color]="$2"
         shift
         shift
@@ -369,64 +422,73 @@ parse_requirements() {
         exit 1
       fi
       ;;
-  
+
     # :flag.case
     --save | -s )
+      # :flag.conflicts
+      # :flag.case_no_arg
       args[--save]=1
       shift
       ;;
-  
+
     # :flag.case
     -1 )
+      # :flag.conflicts
+      # :flag.case_no_arg
       args[-1]=1
       shift
       ;;
-  
+
     # :flag.case
     -2 )
+      # :flag.conflicts
+      # :flag.case_no_arg
       args[-2]=1
       shift
       ;;
-  
-  
-    -* )
+
+    -?* )
       printf "invalid option: %s\n" "$key"
       exit 1
       ;;
-  
+
     * )
       # :command.parse_requirements_case
+      # :command.parse_requirements_case_simple
       printf "invalid argument: %s\n" "$key"
       exit 1
       ;;
-  
+
     esac
   done
+  # :command.required_args_filter
+  # :command.required_flags_filter
+  # :command.catch_all_filter
   # :command.default_assignments
-  [[ -n ${args[--color]} ]] || args[--color]="auto"
+  [[ -n ${args[--color]:-} ]] || args[--color]="auto"
+  # :command.whitelist_filter
+  # :command.user_filter
 }
 
 # :command.initialize
 initialize() {
-  version="0.1.10"
+  version="0.1.11"
   long_usage=''
-  set -e  
+  set -e
 
-  # :src/initialize.sh
+  # src/initialize.sh
   verify_git_repo
 }
 
 # :command.run
 run() {
-  declare -A args
-  parse_requirements "$@"
+  declare -A args=()
+  declare -a other_args=()
+  declare -a input=()
+  normalize_input "$@"
+  parse_requirements "${input[@]}"
 
-  if [[ ${args[--version]} ]]; then
-    version_command
-  elif [[ ${args[--help]} ]]; then
-    long_usage=yes
-    git-changelog_usage
-  elif [[ $action == "root" ]]; then
+  if [[ $action == "root" ]]; then
     root_command
   fi
 }
