- Fix error with multiple `break` comments

diff --git a/git-changelog b/git-changelog
--- a/git-changelog
+++ b/git-changelog
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.7 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.3.4 (https://bashly.dev)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
-if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-  printf "bash version 4 or higher is required\n" >&2
+if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2))); then
+  printf "bash version 4.2 or higher is required\n" >&2
   exit 1
 fi
 
@@ -65,6 +65,7 @@ git_changelog_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_flags
@@ -175,10 +176,16 @@ abort() {
 }
 
 # src/lib/colors.sh
+enable_auto_colors() {
+  if [[ -z ${NO_COLOR+x} && ! -t 1 ]]; then
+    NO_COLOR=1
+  fi
+}
+
 print_in_color() {
   local color="$1"
   shift
-  if [[ -z ${NO_COLOR+x} ]]; then
+  if [[ "${NO_COLOR:-}" == "" ]]; then
     printf "$color%b\e[0m\n" "$*"
   else
     printf "%b\n" "$*"
@@ -225,7 +232,7 @@ get_break_content() {
   local filename="$1"
   local start_line
 
-  start_line=$(grep -n "<!-- break .* -->" "$filename" | cut -d':' -f1)
+  start_line=$(grep -n "<!-- break .* -->" "$filename" | head -n1 | cut -d':' -f1)
 
   if [[ -n "$start_line" ]]; then
     sed -n "${start_line},\$p" "$filename"
@@ -413,6 +420,8 @@ verify_git_repo() {
 
 # :command.parse_requirements
 parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -553,13 +562,8 @@ parse_requirements() {
 
 # :command.initialize
 initialize() {
-  version="0.3.2"
-  long_usage=''
+  declare -g version="0.3.2"
   set -e
-
-  # :command.globals
-  declare -g -A args=()
-  declare -g -a input=()
 
   # src/initialize.sh
 
@@ -567,6 +571,11 @@ initialize() {
 
 # :command.run
 run() {
+  # :command.globals
+  declare -g long_usage=''
+  declare -g -A args=()
+  declare -g -a input=()
+
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
@@ -575,5 +584,7 @@ run() {
   esac
 }
 
+# :command.start
+command_line_args=("$@")
 initialize
-run "$@"
+run "${command_line_args[@]}"
